### ISSUE TITLE
Missing icons in Builder when using Font Awesome v5

### ISSUE THREAD

**Issue by gladkiy** [formio/formio.js#1991]
I use UI theme where I have built-in Font Awesome v5.
And when I implement Builder I see missing icons:
![2019-10-31_1231_001](https://user-images.githubusercontent.com/10575605/67935499-ff872500-fbda-11e9-9975-ddad565eec07.png)

Are you going to update Font Awesome to v5? Thanks in advance.

**Comment by gladkiy** [comment]
I have error for some reasons in live example https://stackblitz.com/edit/angular-mqzhxv
But I can list missing icons in Font Awesome v5:
- fa fa-dot-circle-o
- fa fa-clock-o
- fa fa-usd
- fa fa-pencil
- fa fa-html5
- fa fa-folder-o
- fa fa-square-o
- fa fa-refresh
- fa fa-files-o
- fa fa-wpforms

**Comment by wag110894** [comment]
Thanks for reaching out!
We have added this item to our 4x backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.

**Comment by hisuwh** [comment]
Did anyone work out a fix for this?  I'm missing radio icon:
![image](https://user-images.githubusercontent.com/4470351/89032186-07bbee80-d32c-11ea-8297-dd24602a61af.png)

And the move and remove icons:
![image](https://user-images.githubusercontent.com/4470351/89032211-13a7b080-d32c-11ea-9618-e89d6f6cb120.png)

**Comment by wag110894** [comment]
This item is still on our backlog. As mentioned above, we welcome a pull request or have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.

**Comment by hisuwh** [comment]
Looking at this a bit more closely seems some of these icons have been made pro in v5 or just removed/renamed completely.  I've just fixed some in my own project but redirecting the classes to the available icons using the scss mixins and variables:

```scss
@import "~@fortawesome/fontawesome-free/scss/fontawesome.scss";
@import "~@fortawesome/fontawesome-free/scss/solid.scss";
@import "~@fortawesome/fontawesome-free/scss/regular.scss";

.fa.fa-remove {
    &:before {
        content: fa-content($fa-var-times);
    }
}

.fa.fa-arrows {
    &:before {
        content: fa-content($fa-var-arrows-alt);
    }
}

.fa.fa-dot-circle-o {
    @extend .far;

    &:before {
        content: fa-content($fa-var-dot-circle);
    }
}
```

Not sure how would be best to fix this within formio itself as I guess you'll still need to handle people using v4.  Hopefully the above approach can help some people fix this in their own projects though.
