### ISSUE TITLE
Formio dialog close icon not rendering correctly

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#448]
Extra escape character in `src/sass/formio.form.scss` is causing bad render of close icon on formio dialog

```scss
src/sass/formio.form.scss

/* Line 318 */
.formio-dialog-close:before {
  font-family: 'Helvetica', Arial, sans-serif;
  content: '\\00D7';
  cursor: pointer;
}

/* Line 427 */
.formio-dialog.formio-dialog-theme-default .formio-dialog-close:before {
  display: block;
  padding: 3px;
  background: transparent;
  color: #bbb;
  content: '\\00D7';
  font-size: 26px;
  font-weight: 400;
  line-height: 26px;
  text-align: center;
}
```

The correct `content` value should be `\00D7`
