### ISSUE TITLE
[RTL] Useful styles for RTL support

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#805]
I have created some styles for some components struggling with RTL languages (e.g. Arabic, Hebrew).

I hope you find it useful and if you find something else please let me know.

*[SCSS](https://ghostbin.com/paste/q8hnq)*

```scss
[dir=rtl] {
  text-align: right;

  .formio-component {
    &.formio-component-selectboxes, &.formio-component-radio { 
      > .form-group {
        text-align: right;
      }
    }

    &.formio-component-datetime {
      .flatpickr-input {
          text-align: right;
      }
    }
  }

  .choices {
    &:after {
      right: unset;
      left: 11.5px;
    }

    .choices__list {
      .choices__item {
        text-align: right;

        img {
          float: right;
        }

        button.choices__button {
          left: 0;
          right: unset;
          margin-right: unset;
          margin-left: 25px;
          overflow: hidden;
        }
      }

      &.choices__list--dropdown {
        > input.choices__input {
          text-align: right;
        }
        .choices__item--selectable {
          padding-right: 10px;
          padding-left: 0;
        }
      }

      &.choices__list--multiple {
        float: right;

        .choices__item {

          button.choices__button {
            float: left;
            margin: 0 8px 0 -4px;
            padding-left: unset;
            padding-right: 16px;
            border-left: none;
            border-right: 1px solid #008fa1;
          }
        } 
      }
    }
  }
}
```

*[CSS]( https://ghostbin.com/paste/q8hnq)*:

```css
[dir=rtl] {
  text-align: right;
}
[dir=rtl] .formio-component.formio-component-selectboxes > .form-group,
[dir=rtl] .formio-component.formio-component-radio > .form-group {
  text-align: right;
}
[dir=rtl] .formio-component.formio-component-datetime .flatpickr-input {
  text-align: right;
}
[dir=rtl] .choices:after {
  right: unset;
  left: 11.5px;
}
[dir=rtl] .choices .choices__list .choices__item {
  text-align: right;
}
[dir=rtl] .choices .choices__list .choices__item img {
  float: right;
}
[dir=rtl] .choices .choices__list .choices__item button.choices__button {
  left: 0;
  right: unset;
  margin-right: unset;
  margin-left: 25px;
  overflow: hidden;
}
[dir=rtl] .choices .choices__list.choices__list--dropdown > input.choices__input {
  text-align: right;
}
[dir=rtl] .choices .choices__list.choices__list--dropdown .choices__item--selectable {
  padding-right: 10px;
  padding-left: 0;
}
[dir=rtl] .choices .choices__list.choices__list--multiple {
  float: right;
}
[dir=rtl] .choices .choices__list.choices__list--multiple .choices__item button.choices__button {
  float: left;
  margin: 0 8px 0 -4px;
  padding-left: unset;
  padding-right: 16px;
  border-left: none;
  border-right: 1px solid #008fa1;
}

```
