### ISSUE TITLE
Remove extra spaces in component's text nodes

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#807]
There are a couple of components which does not allow labels or strings to be translated because they prepend or append extra spaces.  This adds an extra difficulty when trying to create translations for these labels as extra spaces needs to be considered and if you are using Form.io to store your translations, because Form.io trims input strings, you will not be able to translate these labels.

Extra spaces should be removed and in return use CSS styles to make up for these changes.

The following components presents this problem:

## File Component

https://github.com/formio/formio.js/blob/1d4d1953599f8c4c8ec03d5d00920b4c4a731841/src/components/file/File.js#L411

#### CSS Fix

The following CSS styles should be implemented to achieve the same result:

```css
.formio-component-file .fileSelector .browse {
    cursor: pointer;
    margin-left: 5px;
}

[dir=rtl] .formio-component-file .fileSelector .browse {
    margin-left: unset;
    margin-right: 5px;
}

[dir=rtl] i.glyphicon.glyphicon-cloud-upload {
    margin-right: unset;
    margin-left: 5px;
}
```

## Panel Component

https://github.com/formio/formio.js/blob/1d4d1953599f8c4c8ec03d5d00920b4c4a731841/src/components/panel/Panel.js#L87

#### CSS Fix

The following CSS styles should be implemented to achieve the same result:

```css
.formio-collapse-icon {
  margin-right: 5px;
}

[dir=rtl] .formio-collapse-icon {
  margin-right: unset;
  margin-left: 5px;
}
```

## Base Component

This are special cases as the it relies on code that [has not been updated since January](https://github.com/formio/formio.js/commit/e4e06c7b2ef83e6411fbb3211a6d544076c9237b).  Data Grid component uses the Base component addButton function to create the Add Another button.  Resource component use a modified version of the Base Component's addButton function but it basically creates a button element prepending an additional space.

https://github.com/formio/formio.js/blob/ae74185e731fd9ca099aac2ad331219a98b2dbf8/src/components/base/Base.js#L890-L912

https://github.com/formio/formio.js/blob/ae74185e731fd9ca099aac2ad331219a98b2dbf8/src/components/resource/Resource.js#L47-L72

The Edit Grid component also has an Add Another button, but it uses its own function which is an updated version of the addButton function of the base component.  The Edit Grid component does not have the problem of the Data Grid or Resource component because the additional space is added in a separate DOM Text Node, thus not affecting translations nor RTL display.

https://github.com/formio/formio.js/blob/2e7faf623506bcd41155fd5784814fd5407a14df/src/components/editgrid/EditGrid.js#L275-L291

The addButton function in Base Component should be replaced by Edit Grid component's createAddButton function.  The logic of adding extra spaces as separate Text Node could also be implemented in other cases.
