### ISSUE TITLE
Bootstrap 4 / icons

### ISSUE THREAD

**Issue by rauwebieten** [formio/formio.js#991]
I followed the simple example, using bootstrap 4.

I see the submit button still uses glyphicons, which are no available in bootstrap 4.
Also i set Formio.icons = 'fontawesome'; but that did not help.

```html
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://unpkg.com/formiojs@latest/dist/formio.full.min.css">
    <script src="https://unpkg.com/formiojs@latest/dist/formio.full.min.js"></script>
    <script type="text/javascript">
        window.onload = function() {
            Formio.icons = 'fontawesome';
            Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example');
        };
    </script>
</head>
<body>
<div class="container">
    <div id="formio"></div>
</div>
</body>
</html>
```

Screenshot result:
https://screenshotscdn.firefoxusercontent.com/images/7d6cd604-834e-438b-86f1-62a4120510df.png

Css code that triggers this:
```css
.formio-component-submit .submit-fail::after {

    font-family: 'Glyphicons Halflings';
    content: '\e014';
    position: relative;
    right: -4px;
    top: 1;
    line-height: 1;

}
```

**Comment by rauwebieten** [comment]
Anyone interested in a quick fix:

```css
.formio-component-submit .submit-success::after {
    font-family: 'FontAwesome';
    content: '\f00c';
}
.formio-component-submit .submit-fail::after {
    font-family: 'FontAwesome';
    content: '\f00d';
}
```

**Comment by travist** [comment]
Thank you! We will add this fix to our next release.

**Comment by rauwebieten** [comment]
What does the setting actually do?
```Formio.icons = 'fontawesome';```

I noticed in the CSS file, there are plenty more references to glyphicons. They should all be converted to fontawesome, or made configurable I think.

**Comment by travist** [comment]
It globally sets the font icon set for all rendered forms within that application. This controls the following method.

https://github.com/formio/formio.js/blob/master/src/Component.js#L459

and is set here.

https://github.com/formio/formio.js/blob/master/src/Webform.js#L20

**Comment by rauwebieten** [comment]
If you want the icon-lib parametrisable (is that a word?), you should also make the css-file aware of this.
Something like:
```css

.formio-glyphicons .formio-component-submit .submit-fail::after {
    font-family: 'Glyphicons Halflings';
    content: '\e014';
}

.formio-fontawesome .formio-component-submit .submit-fail::after {
    font-family: 'FontAwesome';
    content: '\f00d';
}

etc...

```

Or, totally remove all icon related stuff from CSS and move it to JS.
